disabled_rules:
- force_cast
- identifier_name
- line_length
- shorthand_operator
- trailing_whitespace
- type_name

excluded:
  # AppDelegate, SceneDelegate file 무시
  - Mukjipsa-iOS/Resource/Support/AppDelegate.swift
  - Mukjipsa-iOS/Resource/Support/SceneDelegate.swift
